# This is used by the action https://github.com/dorny/paths-filter
docker: &docker
  - added|modified: './docker/**/*'
  - added|modified: './docker/*'

dependencies: &dependencies
  - 'pyproject.toml'

actions: &actions
  - added|modified: './.github/**/*'

python: &python
  - added|modified: 'src/**'
  - added|modified: 'tests/**'
  - 'manage.py'

changelog:
  - added|modified: 'changes/**'
  - 'CHANGELOG.md'

mypy:
  - *python
  - 'mypy.ini'

run_tests:
  - *actions
  - *python
  - *docker
  - *dependencies
  - 'pytest.ini'
  - 'tox.ini'

package: &package
  - *python
  - *dependencies

dockerize:
  - *package
  - *docker
  - '.github/workflows/test.yml'
  - '.github/workflows/dockerize.yml'

migrations:
  - added|modified: 'src/**/migrations/*'

code_settings: &code_settings
  - '.pre-commit-config.yaml'
  - 'pytest.ini'
  - 'tox.ini'
  - 'pyproject.toml'
  - 'ruff.toml'
  - 'mypy.toml'


lint:
  - *python
  - *code_settings

docs:
  - added|modified: './docs/**/*'
  - modified: '.mkdocs.yml'
  - modified: './src/birder/config/__init__.py'
  - modified: './github/workflows/docs.yml'
  - modified: './github/file-filters.yml'

version:
  - './src/krm3/__init__.py'
