[tool.poetry]
name = "krm3"
version = "0.1.0"
description = "KRM3"
authors = ["K-Tech team"]
packages = [
    { include = "krm3", from="src" },
]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^3"
sentry-sdk = "^1"
psycopg2-binary = "^2"
django-click = "^2.3.0"
django-regex = "^0.5.0"
django-mptt-admin = "^2.4.1"
django-smart-admin = {version = "^2.6.0", extras = ["full"]}
pyoxr = "^1.6"
requests = "^2.28.2"
django-debug-toolbar = "^4.0"
django-crispy-forms = "^2.0"
pyyaml = "^6.0"
djoser = "^2.1.0"
django-cors-headers = "^3.14.0"
django-filter = "^23.1"
markdown = "^3.4.3"
drf-spectacular = "^0.26.1"
djangorestframework-camel-case = "^1.4.2"
natural-keys = "^2.0.0"
pytest = "^7.3.1"
pytest-param = "^0.1.1"
parametrize = "^0.1.1"
django-environ = "^0.10.0"

[tool.poetry.group.dev.dependencies]
bumpversion = "^0.6.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pre-commit = "^3.1.1"
pydocstyle = "^6.3.0"
detect-secrets = "^1.4.0"
django-extensions = "^3.2.1"
pdbpp = "^0.10.3"
ruff = "^0.0.265"

[tool.poetry.group.test.dependencies]
pytest-django = "^4.5.2"
pytest-cov = "^4.0.0"
pytest-race = "^0.2.0"
django-factory-boy = "^1.0.0"
django-webtest = "^1.9.10"
pytest-env = "^0.8.1"
pytest-dotenv = "^0.5.2"

[tool.poetry.group.image]
optional = true

[tool.poetry.group.image.dependencies]
circus = "^0.18.0"
uwsgi = "^2.0.21"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"
