[tool.poetry]
name = "krm3"
version = "0.1.0"
description = "KRM3"
authors = ["K-Tech team"]
packages = [
    { include = "krm3", from="src" },
]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3"
django-click = "^2.2.0"
django-environ = "^0.8"
django-regex = "^0.4.1"
sentry-sdk = "^1"
uwsgi = "^2"
psycopg2 = "^2"

[tool.poetry.dev-dependencies]
bumpversion = "^0.6.0"
flake8 = "^4"
ipython = "^8"
isort = "^5.8.0"
pre-commit = "^2.1.1"
pytest = "^7"
pytest-coverage = "*"
pytest-django = "^4"
pytest-echo = "^1.7.1"
pytest-pythonpath = "^0.7.3"
tox = "^3.14.5"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
