[tool.poetry]
name = "krm3"
version = "0.14.1"
description = "KRM3"
authors = ["K-Tech team"]
packages = [
    { include = "krm3", from="src" },
]

[tool.poetry.dependencies]
python = "^3.11"
sentry-sdk = "^1"
django-click = "^2.3.0"
django-regex = "^0.5.0"
django-mptt-admin = "^2.4.1"
django-smart-admin = {version = "^2.6.0", extras = ["full"]}
pyoxr = "^1.6"
requests = "^2.28.2"
django-debug-toolbar = "^4.0"
django-crispy-forms = "^2.0"
pyyaml = "^6.0"
djoser = "^2.1.0"
django-cors-headers = "^4.2.0"
django-filter = "^23.1"
markdown = "^3.4.3"
drf-spectacular = "^0.27.0"
djangorestframework-camel-case = "^1.4.2"
natural-keys = "^2.0.0"
parametrize = "^0.1.1"
django-environ = "^0.11.2"
django-qr-code = "^4.0.1"
cryptography = "*"
docutils = "^0.20.1"
django-tables2 = "^2.5.3"
tabulate = "^0.9.0"
django-constance = "^3.1.0"
django-picklefield = "^3.1"
django-admin-rangefilter = "^0.12.0"
django = "<6"
django-adminfilters = "^2.4.2"
psycopg = {extras = ["binary", "pool"], version = "^3.1.18"}

[tool.poetry.group.dev.dependencies]
bumpversion = "^0.6.0"
flake8 = "^7.0.0"
isort = "^5.12.0"
pre-commit = "^3.1.1"
pydocstyle = "^6.3.0"
detect-secrets = "^1.4.0"
django-extensions = "^3.2.1"
pdbpp = "^0.10.3"
ruff = "^0.2.2"
opencv-python = "^4.7.0.72"
typing-extensions = "*"

[tool.poetry.group.test.dependencies]
pytest-param = "^0.1.1"
pytest-django = "^4.5.2"
pytest-cov = "^4.0.0"
pytest-race = "^0.2.0"
django-factory-boy = "^1.0.0"
django-webtest = "^1.9.10"
pytest-env = "^1.0.1"
pytest-dotenv = "^0.5.2"
responses = "^0.25.0"

[tool.poetry.group.image]
optional = true

[tool.poetry.group.image.dependencies]
circus = "^0.18.0"
uwsgi = "^2.0.21"
opencv-python-headless = "^4.7.0.72"

[build-system]
requires = ["poetry-core>=1.7.1"]
build-backend = "poetry.core.masonry.api"
