[tool.poetry]
name = "krm3"
version = "0.1.0"
description = "KRM3"
authors = ["K-Tech team"]
packages = [
    { include = "krm3", from="src" },
]

[tool.poetry.dependencies]
python = "^3.11"
Django = "^3"
sentry-sdk = "^1"
uwsgi = "^2"
psycopg2-binary = "^2"
django-click = "^2.3.0"
django-environ = "^0.9.0"
django-regex = "^0.5.0"
django-mptt-admin = "^2.4.1"
django-smart-admin = {version = "^2.6.0", extras = ["full"]}
pyoxr = "^1.6"
requests = "^2.28.2"
social-auth-app-django = "^5.0.0"
django-debug-toolbar = "^3.8.1"
django-crispy-forms = "^2.0"
pyyaml = "^6.0"
circus = "^0.18.0"

[tool.poetry.group.dev.dependencies]
bumpversion = "^0.6.0"
pytest-django = "^4.5.2"
pytest-cov = "^4.0.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pre-commit = "^3.1.1"
pytest-env = "^0.8.1"
pydocstyle = "^6.3.0"
pytest-race = "^0.2.0"
django-factory-boy = "^1.0.0"
django-webtest = "^1.9.10"
detect-secrets = "^1.4.0"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
