# Generated by Django 3.2.18 on 2023-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('title', models.CharField(max_length=30, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('iso3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('fractional_unit', models.CharField(max_length=20)),
                ('base', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ('iso3',),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('rates', models.JSONField(default=dict)),
            ],
        ),
    ]
