# Generated by Django 3.2.18 on 2023-02-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krm3', '0002_auto_20230228_0857'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='resource',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='krm3.resource'),
            preserve_default=False,
        ),
    ]
