# Generated by Django 4.2.1 on 2023-05-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'permissions': [('view_any_expense', "Can view(only) everybody's expenses"), ('manage_any_expense', "Can view, and manage everybody's expenses")], 'verbose_name_plural': 'expense categories'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'permissions': [('view_any_mission', "Can view(only) everybody's missions"), ('manage_any_mission', "Can view, and manage everybody's missions")]},
        ),
    ]
