# Generated by Django 4.2.1 on 2023-05-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_expensecategory_options_alter_mission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('view_any_expense', "Can view(only) everybody's expenses"), ('manage_any_expense', "Can view, and manage everybody's expenses")]},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'expense categories'},
        ),
    ]
