# Generated by Django 4.2.1 on 2023-05-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('missions', '0003_alter_expense_options_alter_expensecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(blank=True, default='GBP', help_text='Leave blank to inherit from mission.default_currency', on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='default_currency',
            field=models.ForeignKey(default='GBP', on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
            preserve_default=False,
        ),
    ]
