# Generated by Django 4.2.1 on 2023-05-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('missions', '0004_expense_currency_mission_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Leave blank for dafault [EUR]', on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
    ]
