# Generated by Django 4.2.2 on 2023-07-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_mission_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2023, help_text="Leave blank for defaulting to from_date's year"),
            preserve_default=False,
        ),
    ]
