# Generated by Django 4.2.2 on 2023-07-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_active'),
        ('missions', '0006_mission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Leave blank for dafault [EUR]', on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
    ]
