# Generated by Django 4.2.2 on 2023-08-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_alter_mission_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='missions.mission'),
        ),
    ]
