# Generated by Django 4.2.2 on 2023-08-28 11:42

from django.db import migrations, models


def forward(apps, schema_editor):
    DocumentType = apps.get_model('missions', 'DocumentType')
    DocumentType.objects.create(title='Nessun documento')
    DocumentType.objects.create(title='Scontrino')
    DocumentType.objects.create(title='Fattura')
    DocumentType.objects.create(title='Ricevuta')


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_alter_expense_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RunPython(code=forward, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='expense',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=models.deletion.PROTECT, to='missions.documenttype'),
        )
    ]
