# Generated by Django 4.2.4 on 2023-08-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_paymentcategory_personal_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
