# Generated by Django 4.2.7 on 2023-11-30 12:54

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    Reimbursement = apps.get_model('missions', 'Reimbursement')
    for obj in Reimbursement.objects.all():
        obj.resource = obj.expenses.first().mission.resource
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_options'),
        ('missions', '0014_alter_expense_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.resource'),
        ),
        migrations.RunPython(code=forward, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reimbursement',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.resource'),
            preserve_default=False,
        ),
    ]
