# Generated by Django 5.0.1 on 2024-01-14 19:19

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    Mission = apps.get_model('missions', 'Mission')
    Mission.objects.update(status='SUBMITTED')


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_active'),
        ('missions', '0016_alter_mission_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=9),
        ),
        migrations.AlterField(
            model_name='mission',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Set automatically if left blank', null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Leave blank for default [EUR]', null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text="Leave blank for defaulting to from_date's year", null=True),
        ),
        migrations.RunPython(code=forward, reverse_code=migrations.RunPython.noop),
    ]
