# Generated by Django 5.0.2 on 2024-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0017_mission_status_alter_mission_number_and_more_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=9),
        ),
    ]
