# Generated by Django 5.0.2 on 2024-05-31 17:48
import itertools

from django.db import migrations, models


def calculate_number(cls, instance_id: int | None, year: int) -> int:
    qs = cls.objects.filter(year=year, number__isnull=False)
    if instance_id:
        qs = qs.exclude(pk=instance_id)
    nums = [0] + sorted(list(qs.values_list('number', flat=True)))
    ret = list(
        itertools.takewhile(lambda v: v[0] == 0 or v[1] == nums[v[0] - 1] + 1, enumerate(nums))
    )[-1]
    return ret[1] + 1


def forward(apps, schema_editor):
    Reimbursement = apps.get_model('missions', 'Reimbursement')

    for obj in Reimbursement.objects.order_by('issue_date').all():
        num = obj.title.split(',')[-1].strip()
        try:
            num = int(num)
            obj.year = obj.issue_date.year
            obj.number = num
            obj.save()
            print(f'Assigned {obj.number}/{obj.year} to {obj.id} {obj.title}')
        except Exception:
            print(f'Could not assign  {obj.id} {obj.title} : {num}')

    print('Autocalculating')
    for obj in Reimbursement.objects.order_by('issue_date').filter(number__isnull=True):
        obj.year = obj.issue_date.year
        obj.number = calculate_number(Reimbursement, obj.id, obj.year)
        print(f'Calculated {obj.number}/{obj.year} to {obj.id} {obj.title}')
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0018_reimbursement_paid_date_alter_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Set automatically', null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text="Leave blank for defaulting to from_date's year", null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.RunPython(code=forward, reverse_code=migrations.RunPython.noop)
    ]
