# Generated by Django 5.0.2 on 2024-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0019_reimbursement_number_reimbursement_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Set automatically'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=0,
                                              help_text="Leave blank for defaulting to issue_date's year"),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reimbursement',
            constraint=models.UniqueConstraint(models.F('year'), models.F('number'),
                                               name='unique_reimbursement_number'),
        )
    ]
