# Generated by Django 5.2 on 2025-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0020_auto_20240619_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='year',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
