# Generated by Django 5.1.8 on 2025-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0021_alter_reimbursement_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Set automatically if left blank'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='title',
            field=models.CharField(help_text='Set automatically if left blank', max_length=120),
        ),
    ]
