# Generated by Django 5.2 on 2025-04-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_project_end_date_project_metadata_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.TextField(choices=[('open', 'open'), ('closed', 'closed')], default='open')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('initial_capacity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.po')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('basket_title', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.TextField(blank=True, max_length=6, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.TextField(choices=[('work', 'work'), ('travel', 'travel'), ('overtime', 'overtime'), ('on_call', 'on call')], default='work')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('state', models.TextField(choices=[('open', 'open'), ('closed', 'closed')], default='open')),
                ('comment', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.task')),
            ],
            options={
                'verbose_name_plural': 'Time entries',
            },
        ),
        migrations.AddConstraint(
            model_name='po',
            constraint=models.UniqueConstraint(fields=('ref',), name='unique_ref_in_po', nulls_distinct=True),
        ),
    ]
