# Generated by Django 5.1.8 on 2025-04-10 13:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0006_project_end_date_project_metadata_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50)),
                ('is_billable', models.BooleanField(default=True)),
                ('state', models.TextField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN')),
                ('start_date', models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=datetime.UTC))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'verbose_name': 'PO',
                'verbose_name_plural': 'POs',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('initial_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.po')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('basket_title', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.TextField(blank=True, max_length=6, null=True)),
                ('start_date', models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=datetime.UTC))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('work_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_call_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('travel_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sick_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('leave_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('on_call_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('travel_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('rest_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('state', models.TextField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN')),
                ('comment', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='timesheet.task'
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Time entries',
            },
        ),
        migrations.AddConstraint(
            model_name='po',
            constraint=models.UniqueConstraint(fields=('ref', 'project'), name='unique_ref_project_in_po'),
        ),
    ]
