# Generated by Django 5.2 on 2025-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='po',
            options={'verbose_name': 'PO', 'verbose_name_plural': 'POs'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='initial_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='po',
            name='state',
            field=models.TextField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='category',
            field=models.TextField(choices=[('WORK', 'Work'), ('TRAVEL', 'Travel'), ('OVERTIME', 'Overtime'), ('ON CALL', 'On call')], default='WORK'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='state',
            field=models.TextField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN'),
        ),
    ]
