# Generated by Django 5.1.8 on 2025-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='travel_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
