# Generated by Django 5.1.8 on 2025-04-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_basket_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='follows',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='followed_by', to='timesheet.basket'),
        ),
    ]
