# Generated by Django 5.2 on 2025-04-08 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timesheet', '0002_alter_po_options_alter_basket_initial_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=datetime.UTC)),
        ),
    ]
