# Generated by Django 5.1.8 on 2025-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_alter_basket_follows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'permissions': [('view_any_timesheet', "Can view(only) everybody's timesheets"), ('manage_any_timesheet', "Can view, and manage everybody's timesheets")], 'verbose_name_plural': 'Time entries'},
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
