# Generated by Django 3.2.18 on 2023-04-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='first_name',
            field=models.CharField(default='<unknown>', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='last_name',
            field=models.CharField(default='<unknown>', max_length=50),
            preserve_default=False,
        ),
    ]
