# Generated by Django 4.2.1 on 2023-05-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_social_profile_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_any_project', "Can view(only) everybody's projects"), ('manage_any_project', "Can view, and manage everybody's projects")]},
        ),
    ]
