# Generated by Django 5.2 on 2025-05-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reimbursement_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='work_hours',
            new_name='day_shift_hours',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='overtime_hours',
            new_name='night_shift_hours',
        ),
    ]
