# Generated by Django 5.2 on 2025-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_rename_work_hours_timeentry_day_shift_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
    ]
