# Generated by Django 4.2.7 on 2023-12-14 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    Resource = apps.get_model('core', 'Resource')

    for obj in UserProfile.objects.all():
        obj.user.picture = obj.picture
        obj.user.social_profile = obj.social_profile
        obj.user.save()

    for obj in Resource.objects.all():
        if obj.profile:
            obj.user = obj.profile.user
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_country_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(code=forward, reverse_code=migrations.RunPython.noop),
    ]
