# Generated by Django 5.2.1 on 2025-05-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_specialleavereason_timeentry_special_leave_hours_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('day_shift_hours__range', (0, 16))), name='day_shift_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('sick_hours__range', (0, 24))), name='sick_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('holiday_hours__range', (0, 24))), name='holiday_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('leave_hours__range', (0, 24))), name='leave_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('special_leave_hours__range', (0, 24))), name='special_leave_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('night_shift_hours__range', (0, 8))), name='night_shift_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('on_call_hours__range', (0, 24))), name='on_call_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('travel_hours__range', (0, 24))), name='travel_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('rest_hours__range', (0, 24))), name='rest_hours_range'),
        ),
    ]
