# Generated by Django 5.2.1 on 2025-05-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_specialleavereason_timeentry_special_leave_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
