# Generated by Django 5.2.1 on 2025-06-02 05:14
import typing

import django.core.serializers.json
import django_pydantic_field.fields

import krm3
from krm3.core.pyd_models import Hours
from django.db import migrations, models

if typing.TYPE_CHECKING:
    from krm3.core.models import TimeEntry


def forward(apps, schema_editor):
    TE: TimeEntry = apps.get_model('core', 'TimeEntry')
    for obj in TE.objects.all():
        obj.hours = {
            'day_shift': obj.day_shift_hours,
            'night_shift': obj.night_shift_hours,
            'sick': obj.sick_hours,
            'holiday': obj.holiday_hours,
            'leave': obj.leave_hours,
            'special_leave': obj.special_leave_hours,
            'on_call': obj.on_call_hours,
            'travel': obj.travel_hours,
            'rest_hours': obj.rest_hours,
            'special_leave_reason_id': obj.special_leave_reason_id
        }
        obj.save()


def backward(apps, schema_editor):
    TE: TimeEntry = apps.get_model('core', 'TimeEntry')
    for obj in TE.objects.all():
        obj.day_shift_hours = obj.hours.day_shift
        obj.night_shift_hours = obj.hours.night_shift
        obj.sick_hours = obj.hours.sick
        obj.holiday_hours = obj.hours.holiday
        obj.leave_hours = obj.hours.leave
        obj.special_leave_hours = obj.hours.special_leave
        obj.on_call_hours = obj.hours.on_call
        obj.travel_hours = obj.hours.travel
        obj.rest_hours = obj.hours.rest
        obj.special_leave_reason_id = obj.hours.special_leave_reason_id
        obj.save()


default=Hours(day_shift=0.0).model_dump()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_resource_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='day_shift_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='hours',
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=default,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=krm3.core.pyd_models.Hours,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forward, backward),
    ]
