# Generated by Django 5.2.3 on 2025-06-19 14:34

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_timeentry_day_shift_hours_range_and_more'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project__name', 'title']},
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='state',
        ),
        migrations.CreateModel(
            name='TimesheetSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField(help_text='NB: End date is the day after the actual end date')),
                ('closed', models.BooleanField(default=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
            ],
        ),
        migrations.AddField(
            model_name='timeentry',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timesheetsubmission'),
        ),
        migrations.AddConstraint(
            model_name='timesheetsubmission',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('resource', '=')], name='exclude_overlapping_timesheets'),
        ),
    ]
