# Generated by Django 5.2.2 on 2025-07-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_alter_resource_options_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
