# Generated by Django 5.2.2 on 2025-08-13 14:34

import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_resource_first_name_alter_resource_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField(help_text='NB: End date is the day after the actual end date')),
                ('country_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='holidays.code and optionally subdivision from holidays library'), size=None)),
                ('reason', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField(help_text='NB: End date is the day after the actual end date')),
                ('country_calendar_code', models.CharField()),
                ('working_schedule', models.JSONField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('resource', '=')], name='exclude_overlapping_contracts')],
            },
        ),
    ]
