# Generated by Django 5.2.2 on 2025-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_extraholiday_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='bank_from',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='bank_to',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('bank_to__range', (0, 24))), name='bank_to_range'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('bank_from__range', (0, 24))), name='bank_from_range'),
        ),
    ]
