# Generated by Django 5.2.6 on 2025-09-25 13:56

import django.core.validators
import krm3.missions.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contract_country_calendar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment about the contract', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, help_text='Optional PDF document (PDF files only)', null=True, upload_to=krm3.missions.media.contract_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='contract',
            name='meal_vaucher',
            field=models.BooleanField(default=True, help_text='Enable meal voucher for this contract'),
        ),
    ]
