# Generated by Django 5.2.6 on 2025-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contract_comment_contract_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('period',)},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='meal_vaucher',
        ),
        migrations.AddField(
            model_name='contract',
            name='meal_voucher',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resource',
            name='preferred_in_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='protocol_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='working_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
