# Generated by Django 5.2.6 on 2025-10-07 12:47
import datetime
import typing

from django.db import migrations, models


if typing.TYPE_CHECKING:
    from krm3.core.models import Contract, Resource


START_DATE = datetime.date(1996, 4, 1)

def forward(apps, schema_editor) -> None:  # noqa: ANN001
    R: "Resource" = apps.get_model('core', 'resource')  # noqa: N806
    for obj in R.objects.all():
        obj: "Resource"
        if obj.contract_set.count() == 0:
            end_date = None if obj.active else datetime.date(2025, 7, 31)
            obj.contract_set.create(period=(START_DATE, end_date))


def backward(apps, schema_editor) -> None:  # noqa: ANN001
    C: "Contract" = apps.get_model('core', 'Contract')  # noqa: N806
    for obj in C.objects.all():
        if obj.period.lower == START_DATE:
            obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contract_comment_contract_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('period',)},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='meal_vaucher',
        ),
        migrations.AddField(
            model_name='contract',
            name='meal_voucher',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resource',
            name='preferred_in_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='protocol_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='working_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(forward, backward),
    ]
