# Generated by Django 5.2.6 on 2025-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contract_comment_contract_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='protocol_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
