# Generated by Django 5.2.6 on 2025-10-03 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_timeentry_protocol_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(1996, 4, 1)),
            preserve_default=False,
        ),
    ]
