# Generated by Django 5.2.2 on 2025-10-01 13:41
import datetime
import typing

from django.db import migrations

if typing.TYPE_CHECKING:
    from krm3.core.models import Contract, Resource


START_DATE = datetime.date(1996, 4, 1)

def forward(apps, schema_editor) -> None:  # noqa: ANN001
    R: "Resource" = apps.get_model('core', 'resource')  # noqa: N806
    for obj in R.objects.all():
        obj: "Resource"
        if obj.contract_set.count() == 0:
            end_date = None if obj.active else datetime.date(2025, 7, 31)
            obj.contract_set.create(period=(START_DATE, end_date))


def backward(apps, schema_editor) -> None:  # noqa: ANN001
    C: "Contract" = apps.get_model('core', 'Contract')  # noqa: N806
    for obj in C.objects.all():
        if obj.period.lower == START_DATE:
            obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_timeentry_protocol_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('period',)},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RunPython(forward, backward),
    ]
