# Generated by Django 5.2.6 on 2025-10-23 06:51

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetsubmission',
            name='timesheet',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='extraholiday',
            name='period',
            field=django.contrib.postgres.fields.ranges.DateRangeField(help_text='N.B.: End date is the day after the actual end date'),
        ),
        migrations.AlterField(
            model_name='timesheetsubmission',
            name='period',
            field=django.contrib.postgres.fields.ranges.DateRangeField(help_text='N.B.: End date is the day after the actual end date'),
        ),
    ]
