# Generated by Django 5.2.6 on 2025-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='meal_vaucher',
        ),
        migrations.AddField(
            model_name='contract',
            name='meal_voucher',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contract',
            name='preferred_in_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='working_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
