# Generated by Django 5.2.6 on 2025-10-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_timesheetsubmission_timesheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetsubmission',
            name='timesheet',
            field=models.JSONField(default=dict),
        ),
    ]
