# Generated by Django 5.2.6 on 2025-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_timesheetsubmission_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetsubmission',
            name='timesheet',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
