# Generated by Django 5.2.7 on 2025-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20251106_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='vcard_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
