# Generated by Django 5.2.8 on 2025-12-02 10:18
import os
import typing
from pathlib import Path

import magic
from django.conf import settings
from django.db import migrations

from krm3.missions.media import mission_directory_path

if typing.TYPE_CHECKING:
    from krm3.core.models import Expense



def forward(apps, schema_editor):
    E: Expense = apps.get_model('core', 'Expense')
    for instance in E.objects.filter():
        if instance.image.name and instance.image.name.startswith('{') and (pathname := Path(instance.image.path)).exists():
            guess = magic.from_file(instance.image.path)
            suffix = {'JPEG': 'jpg', 'PDF': 'pdf', 'PNG': 'png'}[guess.split(' ')[0]]
            new_name = mission_directory_path(instance, f'{pathname.stem}.{suffix}')
            new_path = Path(settings.MEDIA_ROOT) / new_name
            if new_path.exists():
                raise Exception(f'Failed moving {pathname}, File {new_path} already exists')
            Path(new_path).parent.mkdir(parents=True, exist_ok=True)
            os.rename(pathname, new_path)
            instance.image.name = new_name
            instance.save()
            if instance.image.path != str(new_path):
                raise Exception(f'Failed renaming {pathname}, File {new_path} already exists')

        # obj: R
        # title = obj.title.replace(obj.resource.last_name, '').replace(obj.resource.first_name, '')
        # obj.month = match_month(title)
        # obj.save()

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_resource_vcard_text'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
