# Generated by Django 5.2.8 on 2025-11-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20251202_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
