# Generated by Django 5.2.9 on 2025-12-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_resource_fiscal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('tax_id', models.PositiveIntegerField(blank=True, null=True)),
                ('job_title', models.CharField(max_length=80)),
                ('picture', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Currently Active'), ('LEFT_COMPANY', 'Left Company')], default='ACTIVE', max_length=20)),
                ('addresses', models.ManyToManyField(related_name='contacts', through='core.AddressInfo', to='core.address')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact'),
        ),
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.email')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='emails',
            field=models.ManyToManyField(related_name='contacts', through='core.EmailInfo', to='core.email'),
        ),
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phone')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='phones',
            field=models.ManyToManyField(related_name='contacts', through='core.PhoneInfo', to='core.phone'),
        ),
        migrations.CreateModel(
            name='SocialMediaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('social_media_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.socialmedia')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='social_media_urls',
            field=models.ManyToManyField(related_name='contacts', through='core.SocialMediaInfo', to='core.socialmedia'),
        ),
    ]
