# Generated by Django 5.2.9 on 2025-12-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_address_email_phone_website_addressinfo_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.URLField(blank=True, help_text='Picture URL', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
    ]
