# Generated by Django 5.2.9 on 2025-12-19 14:15

import django.core.validators
import krm3.core.storage
import krm3.missions.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_address_email_phone_website_addressinfo_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('period',), 'permissions': [('view_any_contract', "Can view(only) everybody's contracts"), ('manage_any_contract', "Can view, and manage everybody's contracts")]},
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, help_text='Optional PDF document (PDF files only)', null=True, storage=krm3.core.storage.PrivateMediaStorage, upload_to=krm3.missions.media.contract_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.FileField(blank=True, null=True, storage=krm3.core.storage.PrivateMediaStorage, upload_to=krm3.missions.media.mission_directory_path),
        ),
    ]
