# Generated by Django 5.2.9 on 2025-12-19 15:35

import django.core.validators
import krm3.core.storage
import krm3.missions.media
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_contract_options_alter_contract_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=krm3.core.storage.ProtectedFileField(blank=True, help_text='Optional PDF document (PDF files only)', null=True, protected_url_name='protected_contract', storage=krm3.core.storage.PrivateMediaStorage, upload_to=krm3.missions.media.contract_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=krm3.core.storage.ProtectedFileField(blank=True, null=True, protected_url_name='protected_expense', storage=krm3.core.storage.PrivateMediaStorage, upload_to=krm3.missions.media.mission_directory_path),
        ),
    ]
