# Generated by Django 5.2.9 on 2026-01-12 14:40

import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import krm3.core.models.schedule
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_client_picture_contact_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='meal_voucher',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='working_schedule',
        ),
        migrations.CreateModel(
            name='MealVoucherThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=4), default=krm3.core.models.schedule._default_schedule, help_text="An array of 7 numbers, one for each day of the week, representing scheduled hours for that day. First element is Monday's schedule, second is Tuesday's, ..., last is Sunday's.", size=7)),
                ('non_working_day_hours', models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=4)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_voucher_thresholds', to='core.contract')),
            ],
            options={
                'abstract': False,
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('contract', '=')], name='exclude_overlapping_meal_voucher_thresholds_for_contract')],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=4), default=krm3.core.models.schedule._default_schedule, help_text="An array of 7 numbers, one for each day of the week, representing scheduled hours for that day. First element is Monday's schedule, second is Tuesday's, ..., last is Sunday's.", size=7)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='core.contract')),
            ],
            options={
                'abstract': False,
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('contract', '=')], name='exclude_overlapping_work_schedules_for_contract')],
            },
        ),
    ]
