# Generated by Django 5.2.9 on 2026-01-16 16:42

import django.core.validators
import krm3.core.storage
import krm3.missions.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_client_picture_contact_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, help_text='Optional PDF document (PDF files only)', null=True, storage=krm3.core.storage.PrivateMediaStorage(), upload_to=krm3.missions.media.contract_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.FileField(blank=True, null=True, storage=krm3.core.storage.PrivateMediaStorage(), upload_to=krm3.missions.media.mission_directory_path),
        ),
    ]
