# Generated by Django 5.2.9 on 2025-12-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_client_picture_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='preferred_language',
            field=models.CharField(choices=[('en-uk', 'English'), ('it', 'Italian'), ('fr', 'French'), ('pl', 'Polish')], default='en-uk'),
        ),
    ]
