# Generated by Django 5.2.9 on 2026-02-03 08:56

import django.contrib.postgres.fields
import django.db.models.deletion
import krm3.core.models.schedule
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_use_private_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealVoucherThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=4), default=krm3.core.models.schedule._default_schedule, help_text="An array of 7 numbers, one for each day of the week, representing scheduled hours for that day. First element is Monday's schedule, second is Tuesday's, ..., last is Sunday's.", size=7)),
                ('non_working_day_hours', models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=4), default=krm3.core.models.schedule._default_schedule, help_text="An array of 7 numbers, one for each day of the week, representing scheduled hours for that day. First element is Monday's schedule, second is Tuesday's, ..., last is Sunday's.", size=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='meal_voucher',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='working_schedule',
        ),
        migrations.AddField(
            model_name='contract',
            name='meal_voucher_thresholds',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mealvoucherthresholds'),
        ),
        migrations.AddField(
            model_name='contract',
            name='work_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workschedule'),
        ),
    ]
