# Generated by Django 5.2.9 on 2026-01-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_protecteddocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('period',), 'permissions': [('view_any_contract', "Can view(only) everybody's contracts"), ('manage_any_contract', "Can view, and manage everybody's contracts")]},
        ),
    ]
