# Generated by Django 5.2.11 on 2026-03-03 15:34

import django.core.validators
import krm3.core.fields
import krm3.core.storage
import krm3.missions.media
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_contract_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=krm3.core.fields.DynamicUrlFileField(blank=True, help_text='Optional PDF document (PDF files only)', null=True, storage=krm3.core.storage.PrivateMediaStorage(), upload_to=krm3.missions.media.contract_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], view_name='media-auth:contract-document'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=krm3.core.fields.DynamicUrlFileField(blank=True, null=True, storage=krm3.core.storage.PrivateMediaStorage(), upload_to=krm3.missions.media.mission_directory_path, view_name='media-auth:expense-image'),
        ),
    ]
