# Generated by Django 5.2.11 on 2026-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_resource_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sunday_as_holiday',
            field=models.BooleanField(default=True, help_text='Sunday always a holiday'),
        ),
    ]
