# Generated by Django 5.2.11 on 2026-04-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_resource_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='preferred_language',
            field=models.CharField(choices=[('en-uk', 'English'), ('it', 'Italiano'), ('fr', 'Français'), ('pl', 'Polski')], default='en-uk'),
        ),
        migrations.CreateModel(
            name='DayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day')),
                ('closed', models.BooleanField(default=False, help_text='Submitted')),
                ('is_holiday', models.BooleanField(default=False, help_text='Is Holiday for resource')),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Holiday hours', max_digits=4)),
                ('leave_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Leave hours', max_digits=4)),
                ('special_leave_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Special leave hours', max_digits=4)),
                ('bank_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Bank hours', max_digits=4)),
                ('sick_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('protocol_number', models.CharField(blank=True, null=True)),
                ('due_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Due hours for the day', max_digits=4)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime hours in the day', max_digits=4)),
                ('meal_voucher', models.PositiveIntegerField(help_text='Meal voucher for the day')),
                ('rest_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Rest hours', max_digits=4)),
                ('comment', models.TextField(blank=True, help_text='Notes', null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('resource', models.ForeignKey(help_text='Resource', on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
                ('special_leave_reason', models.ForeignKey(blank=True, help_text='Special leave reason', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.specialleavereason')),
            ],
        ),
    ]
