# Generated by Django 5.2.11 on 2026-06-16 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_contract_sunday_as_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('madam', 'Madam'), ('miss', 'Miss'), ('mister', 'Mister'), ('mrs', 'Mrs'), ('professor', 'Professor')], max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='preferred_language',
            field=models.CharField(choices=[('en-uk', 'English'), ('it', 'Italiano'), ('fr', 'Français'), ('pl', 'Polski')], default='en-uk'),
        ),
    ]
