# Generated by Django 5.2.17 on 2026-09-03 11:54

from django.db import migrations, models


def forward(apps, schema_editor):  # noqa: ANN001
    resource_model = apps.get_model('core', 'Resource')

    for resource in resource_model.objects.all():
        resource.contract_set.update(
            employee=resource.preferred_in_report,
        )


def backward(apps, schema_editor):  # noqa: ANN001
    resource_model = apps.get_model('core', 'Resource')

    for resource in resource_model.objects.all():
        contract = resource.contract_set.order_by('-period').first()

        if contract is not None:
            resource.preferred_in_report = contract.employee
            resource.save(update_fields=['preferred_in_report'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cleanup_post_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='resource',
            name='preferred_in_report',
        ),
    ]