# Generated by Django 5.2.17 on 2026-09-04 10:16

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):  # noqa: ANN001
    country_model = apps.get_model('core', 'Country')
    city_model = apps.get_model('core', 'City')
    contract_model = apps.get_model('core', 'Contract')

    italy, _ = country_model.objects.update_or_create(
        name='Italy',
        defaults={
            'country_calendar_code': 'IT',
        },
    )
    rome, _ = city_model.objects.update_or_create(
        name='Rome',
        country=italy,
        defaults={
            'subdivision_code': 'RM',
        },
    )

    for contract in contract_model.objects.all():
        country_code = (
            contract.country_calendar_code or ''
        ).strip()

        if country_code:
            base = city_model.objects.filter(
                country__country_calendar_code=country_code,
            ).first()
        else:
            base = rome

        if base is not None:
            contract.base = base
            contract.save(update_fields=['base'])


def backward(apps, schema_editor):  # noqa: ANN001
    contract_model = apps.get_model('core', 'Contract')

    contracts = contract_model.objects.select_related(
        'base__country',
    )

    for contract in contracts:
        if contract.base is None:
            contract.country_calendar_code = None
        else:
            country_code = contract.base.country.country_calendar_code
            contract.country_calendar_code = country_code

        contract.save(update_fields=['country_calendar_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_resource_preferred_in_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='subdivision_code',
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='country',
            name='country_calendar_code',
            field=models.CharField(
                blank=True,
                help_text=(
                    'Country calendar code as per '
                    'https://holidays.readthedocs.io/en/latest/#available-countries'
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='contract',
            name='base',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contracts',
                to='core.city',
            ),
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='contract',
            name='country_calendar_code',
        ),
    ]
