# Generated by Django 5.2.17 on 2026-09-04 10:16

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):  # noqa: ANN001
    country_model = apps.get_model('core', 'Country')
    city_model = apps.get_model('core', 'City')
    contract_model = apps.get_model('core', 'Contract')

    bases = {}
    locations = (
        ('Italy', 'IT', 'Rome', 'RM', ('', 'IT', 'IT-RM')),
        ('United Kingdom', 'GB', 'London', 'ENG', ('GB', 'GB-ENG')),
        ('Poland', 'PL', 'Cracow', None, ('PL',)),
        ('India', 'IN', 'Hyderabad', 'TS', ('IN', 'IN-TS')),
    )
    for country_name, country_code, city_name, subdivision, aliases in locations:
        country, _ = country_model.objects.update_or_create(
            name=country_name,
            defaults={'country_calendar_code': country_code},
        )
        city, _ = city_model.objects.update_or_create(
            name=city_name,
            country=country,
            defaults={'subdivision_code': subdivision},
        )
        for alias in aliases:
            bases[alias] = city

    for contract in contract_model.objects.all():
        country_code = (
            contract.country_calendar_code or ''
        ).strip().upper()

        contract.base_in = bases.get(country_code, bases['IT-RM'])
        contract.save(update_fields=['base_in'])


def backward(apps, schema_editor):  # noqa: ANN001
    contract_model = apps.get_model('core', 'Contract')

    contracts = contract_model.objects.select_related(
        'base_in__country',
    )

    for contract in contracts:
        if contract.base_in is None:
            contract.country_calendar_code = None
        else:
            country_code = contract.base_in.country.country_calendar_code
            subdivision_code = contract.base_in.subdivision_code
            if country_code and subdivision_code:
                country_code = f'{country_code}-{subdivision_code}'
            contract.country_calendar_code = country_code

        contract.save(update_fields=['country_calendar_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_resource_preferred_in_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='subdivision_code',
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='country',
            name='country_calendar_code',
            field=models.CharField(
                blank=True,
                help_text=(
                    'Country calendar code as per '
                    'https://holidays.readthedocs.io/en/latest/#available-countries'
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='contract',
            name='base_in',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contracts',
                to='core.city',
            ),
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='contract',
            name='country_calendar_code',
        ),
    ]
