# Generated by Django 5.2 on 2025-04-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Number of hours to charge', max_digits=4)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_entries', to='timesheet.basket')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.invoice')),
            ],
            options={
                'verbose_name_plural': 'Invoice entries',
            },
        ),
    ]
