# Generated by Django 5.1.8 on 2025-04-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentry',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_entries', to='timesheet.basket'),
        ),
        migrations.AddField(
            model_name='invoiceentry',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.invoice'),
        ),
    ]
