---
name: Bandit Security Scan

on:
  push:
    branches:
      - develop
    paths:
      - src/**
      - test/**
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  bandit-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Perform Bandit Analysis
      uses: PyCQA/bandit-action@v1
      with:
        targets: "src/krm3"
